@Test
public void ${1:name}() throws Exception{
	${2}
}

